[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
    "-C", "link-arg=--target=x86_64-linux-gnu",
    "-C", "link-arg=--sysroot=/tmp/x86-64--glibc--stable-2024.02-1/x86_64-buildroot-linux-gnu/sysroot",
    "-C", "link-arg=-fuse-ld=lld",
    "-C", "link-arg=-L/tmp/x86-64--glibc--stable-2024.02-1/x86_64-buildroot-linux-gnu/sysroot/lib",
    "-C", "link-arg=-L/tmp/x86-64--glibc--stable-2024.02-1/x86_64-buildroot-linux-gnu/sysroot/usr/lib",
    "-C", "link-arg=-no-pie",
]
[target.x86_64-unknown-linux-gnu.cc]
cc = "/Users/undivisible/projects/soliloquy/scripts/clang-cross.sh"