export XDG_RUNTIME_DIR="/run/user/$(id -u)"
export SOL_TOKEN="${SOL_TOKEN:-dev-token-change-me}"
export SOL_UI_URL="${SOL_UI_URL:-file:///opt/sol/ui/index.html}"
export SOLILOQUY_SYSTEM_CONFIG="${SOLILOQUY_SYSTEM_CONFIG:-/etc/soliloquy/system.json}"
export SOLILOQUY_GENERATION_FILE="${SOLILOQUY_GENERATION_FILE:-/etc/soliloquy/generation.json}"
export SOLILOQUY_MARK_GOOD_HOOK="${SOLILOQUY_MARK_GOOD_HOOK:-/usr/local/bin/soliloquy-generation-mark-good}"
export SOLILOQUY_UPDATE_STATE="${SOLILOQUY_UPDATE_STATE:-/var/lib/soliloquy/system/update-state.json}"
